version: "2.0"
services:
  auth:
    build: src/auth/
    image: example_jwt_rsa_auth:latest
    ports:
      - "3001:3001"
    volumes:
      - ./src/utils:/home/node/utils:ro
  service:
    build: src/service/
    image: example_jwt_rsa_service:latest
    ports:
      - "3002:3002"
    volumes:
      - ./src/utils:/home/node/utils:ro